#!/bin/bash
# Generates BuildConfig.swift with baked-in configuration from environment variables.
# Usage: AUTH_CLIENT_ID=xxx API_BASE_URL=xxx ./scripts/cli-generate-config.sh

OUTPUT="cli/RxStorageCli/Sources/RxStorageCli/BuildConfig.swift"

AUTH_VALUE="nil"
if [ -n "$AUTH_CLIENT_ID" ]; then
    AUTH_VALUE="\"$AUTH_CLIENT_ID\""
fi

API_VALUE="nil"
if [ -n "$API_BASE_URL" ]; then
    API_VALUE="\"$API_BASE_URL\""
fi

cat > "$OUTPUT" << EOF
// Auto-generated by scripts/cli-generate-config.sh — DO NOT EDIT
enum BuildConfig {
    static let authClientID: String? = $AUTH_VALUE
    static let apiBaseURL: String? = $API_VALUE
}
EOF
